/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'calvinhuynh' at '10/10/16 10:35 AM' with Gradle 2.14.1
 *
 * @author calvinhuynh, @date 10/10/16 10:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
